export const OPEN_ORDER_PLACING_MODAL = 'REDUX_SAGA_OPEN_ORDER_PLACING_MODAL';
export const CLOSE_ORDER_PLACING_MODAL = 'REDUX_SAGA_CLOSE_ORDER_PLACING_MODAL';
export const SET_PRODUCT_ITEM_ORDER_PLACING =
  'REDUX_SET_PRODUCT_ITEM_ORDER_PLACING';
